apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      env: grafana
  template:
    metadata:
      labels:
        env: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: pvc
          mountPath: /var/lib/grafana
      volumes:
        - name: pvc
          persistentVolumeClaim:
            claimName: pvcforgrafana
