apiVersion: v1
kind: ConfigMap
metadata:
  name: configmapforprometheus
  labels:
    env: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 10s
      evaluation_interval: 10s
    scrape_configs:
      - job_name: 'localhost'
        static_configs:
        - targets: ['localhost:9090']

      - job_name: 'RHEL8'
        static_configs:
        - targets: ['192.168.99.102:9100']
